### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by chethanparameshwara** [e-sha/EV_FlowNet#1]
Hi Evgeny, 

Thank you for this great repo. Do you have the training code and would you be willing to release it? I didn't find it in this repo. If, in case I missed it, could you point me to relevant files?

**Comment by e-sha** [comment]
Dear @analogicalnexus,
Sorry for the delayed reply, I have missed your message.
I'm going to publish training code, but in another repo.

**Comment by e-sha** [comment]
Dear @analogicalnexus,
You can find training code [hear](https://github.com/e-sha/dvs_of_training_framework).
